sudo: false
language: node_js
node_js: '0.10'
script:
- travis-lint .travis.yml
- jscs .
- jshint . --exclude-path .gitignore
- npm test
- make codeclimate
cache:
  directories:
  - node_modules
env:
  global:
    secure: hh+oEEQ20L4buKaZscQ6eBNy61JeWlMGBsx+f2RwFR7BZLCfCbh6gXgMnvdtLcRAHwhK5GuBJM2GhJUPNf1accfT4RAIVNj4K+oXrbCTyHI3+wpm38pSuCrqELe54uod42czbbnp7woZ4Sr5lo1APY8KMs0p1P1pAZ70bqQgINM=
